name: Book Recognizer Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.10.6]

    env:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
      GOOGLE_BOOKS_BASE_URL: ${{ secrets.GOOGLE_BOOKS_BASE_URL }}
      GOOGLE_BOOKS_URL_SUFFIX: ${{ secrets.GOOGLE_BOOKS_URL_SUFFIX }}
      JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      REGION: ${{ secrets.REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: .pip_cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Download pip dependencies
      run: pip download --cache-dir .pip_cache --requirement requirements.txt

    - name: Install setuptools and wheel
      run: pip install setuptools wheel

    - name: Install dependencies
      run: pip install --no-index --find-links .pip_cache -r requirements.txt

    - name: Install PyTorch, torchvision, and torchaudio
      run: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

    - name: Install GroundingDINO
      run: |
        cd GroundingDINO
        pip install -e .
        cd ..

    - name: Create checkpoints directory and download checkpoints
      run: |
        mkdir checkpoints
        curl -L https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth -o checkpoints/sam_vit_h_4b8939.pth
        curl -L https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth -o checkpoints/groundingdino_swint_ogc.pth

    - name: Run tests
      run: pytest